[server]
hostname = "localhost"

[server.listener."smtp"]
bind = ["0.0.0.0:2525"]
protocol = "smtp"

[server.listener."submission"]
bind = ["0.0.0.0:587"]
protocol = "smtp"

[server.listener."imap"]
bind = ["0.0.0.0:993"]
protocol = "imap"

[server.listener."http"]
bind = ["0.0.0.0:8080"]
protocol = "http"

[storage]
data = "sqlite"
fts = "sqlite"
blob = "sqlite"
lookup = "sqlite"
directory = "internal"

[store."sqlite"]
type = "sqlite"
path = "/home/mrahat/Documents/Email server/stalwart/data/stalwart.db"

[directory."internal"]
type = "internal"
store = "sqlite"

[tracer."stdout"]
type = "stdout"
level = "info"
ansi = false
enable = true
